{% set name = "pyxel-sim" %}
{% set version = "0.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyxel-sim-{{ version }}.tar.gz
  sha256: 970fdb85ff044d28e4c5e5338eb6bc1cc2eb9786972b9bf782ced278a5e96548

build:
  number: 0
  noarch: python
  entry_points:
    - pyxel = pyxel.run:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=39.2
    - wheel >=0.29.0
  run:
    - astropy >=4
    - bokeh
    - dask-core
    - fsspec
    - h5py
    - holoviews
    - ipywidgets >=7.5
    - jupyterlab
    - matplotlib-base >=3.1
    - notebook
    - numba
    - numpy >=1.17
    - openpyxl
    - pandas
    - pillow
    - pympler
    - python >=3.6
    - pyyaml
    - scikit-image
    - scipy
    - seaborn
    - tqdm
    - typing-extensions
    - xarray
    - xlrd
    - pygmo

test:
  imports:
    - pyxel
    - pyxel.calibration
  commands:
    - pip check
    - pyxel --help
  requires:
    - pip

about:
  home: https://esa.gitlab.io/pyxel/
  summary: Pyxel detector simulation framework.
  dev_url: https://gitlab.com/esa/pyxel
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - AddYourGitHubIdHere
